name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 2,13 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install ddddocr
          pip3 install dingtalkchatbot
      - name: Clock In
        env:
          URL: ${{ secrets.URL }}
          KEY: ${{ secrets.KEY }}
        run: |
          python3 clock-in.py ${KEY} ${URL} ${{ secrets.SJL }} ${{ secrets.WHY }}
